packages:
  - studio

overrides:
  rollup: ^4.59.0
  picomatch@^2: 2.3.2
  adm-zip: 0.6.0

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
